arch : amd64
os : linux
language : generic
dist : focal
cache : ccache
addons:
    apt:
    - bc
    - bison 
    - build-essential   
    - curl 
    - flex
    - g++-multilib 
    - gcc-multilib 
    - git
    - gnupg 
    - gperf 
    - imagemagick 
    - lib32ncurses5-dev 
    - lib32readline-dev 
    - lib32z1-dev 
    - liblz4-tool 
    - libncurses5 
    - libncurses5-dev 
    - libsdl1.2-dev 
    - libssl-dev 
    - libxml2 
    - libxml2-utils 
    - lzop 
    - pngcrush 
    - rsync 
    - schedtool 
    - squashfs-tools 
    - xsltproc 
    - zip 
    - zlib1g-dev
stages:
  - Get_Files
  - Build
jobs:
    include: 
      - stage: Get_Files
        script: . get_files.sh
        cache:
          directories:
            - $HOME/TWRP
      - stage: Build
        script: . build_ci.sh
